### ISSUE TITLE
GLOBUS-Dataset download probelm

### ISSUE THREAD

**Issue by chke097** [j-duan/VS-Net#3]
Hello, I was replicating your code recently, but there was a problem in downloading the data set. I could not download it directly from the data set link you gave me in GLOBUS. After many attempts, I was reminded that the download failed. So, do you have any other downloading methods? Thank you!

**Comment by VincyDa** [comment]
> Hello, I was replicating your code recently, but there was a problem in downloading the data set. I could not download it directly from the data set link you gave me in GLOBUS. After many attempts, I was reminded that the download failed. So, do you have any other downloading methods? Thank you!

我目前利用globus下载了数据集，如果有需要的话，可以从百度网盘取，链接：https://pan.baidu.com/s/1qUDWHTsu8H7sf8FgMoCacg 
提取码：4ny2 
--来自百度网盘超级会员V3的分享

**Comment by chke097** [comment]
哇  谢谢！！！











在 2023-03-14 16:51:37，"VincyDa" ***@***.***> 写道：

Hello, I was replicating your code recently, but there was a problem in downloading the data set. I could not download it directly from the data set link you gave me in GLOBUS. After many attempts, I was reminded that the download failed. So, do you have any other downloading methods? Thank you!

我目前利用globus下载了数据集，如果有需要的话，可以从百度网盘取，链接：https://pan.baidu.com/s/1qUDWHTsu8H7sf8FgMoCacg
提取码：4ny2
--来自百度网盘超级会员V3的分享
